### ISSUE TITLE
Unable to update a filter field of a saved filter

### ISSUE THREAD

**Issue by 0xedward** [facebook/sapp#21]
Thanks for your continued interest in helping us out with Pysa and SAPP, @m0mosenpai and @gracewgao!

## Scenario
Currently, we don't support updating existing SAPP filters. If a user wants to change a field for an existing filter, but keep the name of the filter the same, they would need to delete the filter before re-saving the filter with the same name

For example, suppose we have an existing filter `Test Filter 1` that filters only for `Code==5008` and we want to overwrite `Test Filter 1` to only filter for `Code==5003`. We expect to perform this action by loading the saved filter `Test Filter 1`, changing the value of `code` from `5008` to `5003`, and finally saving the change to `Test Filter 1`. However to perform this action now, we will need to delete `Test Filter 1`, set the `code` to filter for `5003`, and save a new filter with the same name `Test Filter 1`

## Steps to Reproduce
1. Set up your dev virtual environment
```
git clone git@github.com:facebook/sapp.git && cd sapp
python3 -m venv ~/.venvs/sapp
source ~/.venvs/sapp/bin/activate
pip3 install -r requirements.txt
cd sapp/ui/frontend && npm install
npm run-script build
```
2. Run Pysa on a repo and store the results to pass into SAPP to ingest
```
pyre analyze --no-verify --save-results-to .
```
3. Use SAPP to ingest the results from the Pysa run
```
python3 -m sapp.cli analyze taint-output.json
```
4. Run SAPP server and go to http://localhost:5000
```
python3 -m sapp.cli server
```
5. Create a filter with for any field (eg. filter for code `5008`) and save the filter as `Test Filter 1`
![image](https://user-images.githubusercontent.com/14011954/120400238-7e8a9500-c30b-11eb-9721-b8b949c8a4c4.png)
6. Fill some different filter fields from the ones you have set in step 5 and save the filter with the same name as in step 5 (e.g. `Test Filter 1`)
7. Notice that the filter fails to overwrite the previously saved filter and you get the following traceback in SAPP server logs
```
2021-06-01 19:03:22,221 [ERROR] Traceback (most recent call last):
...
graphql.error.located_error.GraphQLLocatedError: (sqlite3.IntegrityError) UNIQUE constraint failed: filters.name
[SQL: INSERT INTO filters (name, description, json) VALUES (?, ?, ?)]
[parameters: ('test', None, '{"features":[{"mode":"all of","features":[]}],"codes":[5001]}')]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
```

## Related files
The following list of files that might be good starting points:
- [`sapp/ui/filters.py`](https://github.com/facebook/sapp/blob/master/sapp/ui/filters.py#L80)
- [`sapp/filter.py`](https://github.com/facebook/sapp/blob/master/sapp/filter.py#L136)
- [`sapp/ui/frontend/src/Filter.js`](https://github.com/facebook/sapp/blob/master/sapp/ui/frontend/src/Filter.js#L523)

## Resources
- [What is SAPP?](https://github.com/facebook/sapp#sapp)
- [Debugging dev environment setup](https://pyre-check.org/docs/pysa-quickstart/#common-issues)
- [SAPP Filters docs](https://github.com/facebook/sapp#filters)
- [SAPP dev environment setup](https://github.com/facebook/sapp#development-environment-setup)

**Comment by gracewgao** [comment]
Hi Ed - super excited to be working with you and looking forward to helping out with SAPP any way that I can!

I tried out the steps to reproduce the error yesterday, and I'm having some trouble with Step 5, since the SAPP dashboard comes up empty so that I can't select filter options (see screenshot below)

![Empty SAPP dashboard](https://user-images.githubusercontent.com/38268331/120933116-a0e33080-c6c6-11eb-8bd0-78e37d66b56e.png)

I checked that the `taint.output` file isn't empty and there seem to be no other issues running the steps, so I'm just wondering if I'm missing something here?

Also, feel free to jump in @m0mosenpai if you have any insight on this :)

**Comment by 0xedward** [comment]
Hey @gracewgao, thanks for providing a detailed description of what you've tried so far! 😄 

The filter fields in SAPP's web UI fetch the data from the run you have selected to prepopulate a list of options per filter field. From the screenshot, it seems like `Run 6` doesn't contain any issues, which is likely why there are no options to pick from for the `Codes` field. 

>I checked the Common Issues page and noted that the cat taint-output.json | grep "issue" command returned nothing, although the file itself isn't empty and I think some issues were reported when I ran the pyre analyze command

Ah, your guess at what might be going wrong is in the right direction here! If `cat taint-output.json | grep "issue"` is returning nothing, SAPP is likely not ingesting any issues, which would result in a `Run` being empty and no options fetched to prepopulate filter fields. Though this is strange, since you mentioned there were some issues outputted from `pyre analyze`. Would you be able to provide the `taint-output.json` file you are using so I can look into this?

>Is there perhaps a test repo where I can run the pyre analyze command to ensure issues are reported?

In the meantime, here's some repos I've used for testing while working on SAPP:
- https://github.com/facebook/pyre-check/tree/master/documentation/deliberately_vulnerable_flask_app
  - For `deliberately_vulnerable_flask_app`, make sure you run `setup.sh` before running `pyre init && pyre analyze`
- https://github.com/stephenbradshaw/breakableflask/

Sorry about the setup process being a bit confusing!

**Comment by gracewgao** [comment]
@0xedward Thank you! Running Pyre in the breakableflask repo did the trick, so I think there really weren't any issues the first time I did it, my mistake 😅 I've been able to reproduce the rest of the steps until the end so I'll take a look at the files you linked and see what I can do!
