### ISSUE TITLE
what can i do to apply a list of filters and get a merge results in web interface??

### ISSUE THREAD

**Issue by koftnt** [facebook/sapp#98]
hi all ,I noticed that  a list of filters can be applied to a single list of issues and show me a merged results by Command-Line Interface.
But It seems that web interface don't has this feature.How can i apply  several filters and get a merged reaults in web interface??

**Comment by abishekvashok** [comment]
I don't think there's a simple way to combine multiple filters other than manually selecting each parameter via the web interface :)

`filters` are often written in sense that they pertain to a specific rule. Curious to see of potential use cases in combining multiple filters.

You could however combine a list of filters after exporting via the command line interface to manually import it via the web ui. But that is kinda hacky :P
